### ISSUE TITLE
Image tagging on Docker Hub

### ISSUE THREAD

**Issue by matteocontrini** [MassTransit/docker-rabbitmq#6]
Hello,

would it be possible to have new image builds correctly tagged with a version on Docker Hub?

Currently the most recent build is only present as `latest`, which usually isn't a good idea since you can't pin a specific version when deploying (not even a major version).

Ideally, the last build should have these tags:
- `latest`
- `3`
- `3.11`
- `3.11.18`

Which is actually what was done in the past, looking at the tags history.

Thanks.

**Comment by phatboyg** [comment]
I tried, but it kept tagging the wrong images due to the whole amd64/arm64 platform tags. You're welcome to submit a PR to the build script to get it to tag properly.
